# Generated by Django 3.2.5 on 2021-07-24 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_student_id_dashboard_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='grade',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='group',
            field=models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='year',
            field=models.CharField(choices=[('1', 'First year'), ('2', 'Second year'), ('3', 'Third year')], default='1', max_length=1),
        ),
    ]
